### ISSUE TITLE
建議

### ISSUE THREAD

**Issue by hatelove** [crablin/Day2Homework#1]
完成度極高，也都有注意該重構、可維護性、效能調整的地方。建議如下：
1. 不要試圖把複雜的算法寫成同一行執行完畢，在 debug 上會增加額外的困擾，也會少了一些透過 variable 提升可讀性的機會。
2. 還有兩種極端的測試案例可以試試看能不能進行效能上的優化，一種是 {1, 100, 100, 100, 100}, 一種是 {1000,1,1,1,1}

**Comment by crablin** [comment]
**ISSUE COMPLETE** 
refactor discount rate use dictionary
refactor package total discounts algorithm

[https://github.com/crablin/Day2Homework/commit/765604ee1747eb61f4dbf71aee3650a9156f7a36]()
